package by.martyniuk.hotelbooking.constant;

public class CommandConstant {
    public static final String ID = "id";
    public static final String REDIRECT = "redirect";
    public static final String REFERER = "referer";
    public static final String APARTMENT_NUMBER = "apartmentNumber";
    public static final String APARTMENT_CLASS = "apartmentClass";
    public static final String APARTMENT_FLOOR = "apartmentFloor";
    public static final String ADD_APARTMENT_ERROR = "addApartmentError";
    public static final String RESERVATIONS = "reservations";
    public static final String FREE_APARTMENTS = "freeApartments";
    public static final String APARTMENTS = "apartments";
    public static final String APARTMENT_CLASSES = "apartmentClasses";
    public static final String USER = "user";
    public static final String USERS = "users";
    public static final String RESERVATION_ID = "reservationId";
    public static final String APPROVE_RESERVATION_ERROR = "approveReservationError";
    public static final String SHOW_ADMIN_PAGE_ACTION = "/booking?action=show_admin_page";
    public static final String APARTMENT_ID = "apartmentId";
    public static final String STATUS = "status";
    public static final String TYPE = "type";
    public static final String EDIT_APARTMENT_ERROR = "editApartmentError";
    public static final String DELETE = "delete";
    public static final String UPDATE = "update";
    public static final String NUMBER = "number";
    public static final String FLOOR = "floor";
    public static final String CLASS = "class";
    public static final String VALUE = "value";
    public static final String LOCALE = "locale";
    public static final String PAGE = "page";
    public static final String SHOW_APARTMENT_CLASSES = "/booking?action=show_apartment_classes";
    public static final String APARTMENT_CLASSES_ERROR = "apartmentClassesError";
    public static final String DATE_PATTERN = "dd MMMMM, yyyy";
    public static final String CHECK_IN_DATE = "checkInDate";
    public static final String CHECK_OUT_DATE = "checkOutDate";
    public static final String APARTMENT_CLASS_ID = "apartmentClassId";
    public static final String BOOKING_ERROR = "bookingError";
    public static final String BOOKING_MESSAGE = "bookingMessage";
    public static final String PERSON_AMOUNT = "personAmount";
    public static final String UPDATE_PROFILE_ERROR = "updateProfileError";
    public static final String FIRST_NAME = "firstName";
    public static final String MIDDLE_NAME = "middleName";
    public static final String LAST_NAME = "lastName";
    public static final String PHONE_NUMBER = "phoneNumber";
    public static final String CURRENT_PASSWORD = "currentPassword";
    public static final String NEW_PASSWORD = "newPassword";
    public static final String REPEAT_NEW_PASSWORD = "repeatNewPassword";
    public static final String INDEX = "/index.jsp";
    public static final String EMAIL = "email";
    public static final String PASSWORD = "password";
    public static final String REPEAT_PASSWORD = "repeatPassword";
    public static final String REGISTER_ERROR = "registerError";
    public static final String LOGIN_ERROR = "loginError";
    public static final String ERROR_MESSAGE = "errorMessage";
    public static final String ACTION = "action";
    public static final String SHOW_ERROR_PAGE = "/booking?action=forward&page=error";
}
